import { prisma } from "@/lib/prisma";
import type { Prisma } from "@emailautomation/database";
import {
  createProviderFromEnv,
  AutoTagger,
  UnifiedThreadProcessor,
} from "@emailautomation/ai-engine";
import type { AIProvider } from "@emailautomation/ai-engine";
import type {
  TagAutoRules,
  AIProcessingResult,
  AIBulkProcessingResult,
  ActivityAction,
  TrustLevel,
} from "@emailautomation/shared";
import { TRUST_LEVEL_ORDER } from "@emailautomation/shared";
import { getSenderTrustLevel } from "@/lib/contacts";
import { elevateTrustOnReply } from "@/lib/contacts";

let providerInstance: AIProvider | null = null;

function getProvider(): AIProvider {
  if (!providerInstance) {
    providerInstance = createProviderFromEnv();
  }
  return providerInstance;
}

// --- Activity logging ---

async function logAIActivity(
  teamId: string,
  threadId: string,
  action: ActivityAction,
  metadata: Record<string, unknown> = {}
) {
  await prisma.activityLog.create({
    data: {
      teamId,
      userId: null,
      action,
      targetType: "thread",
      targetId: threadId,
      metadata: metadata as Prisma.InputJsonValue,
    },
  });
}

// --- Auto-reply ---

async function sendAutoReply(
  email: {
    threadId: string;
    fromAddress: string;
    messageId: string;
    references: string[];
    subject: string;
  },
  draftBody: string,
  mailboxId: string
) {
  const { SmtpClient } = await import("@emailautomation/mail-engine");
  const { decrypt } = await import("@emailautomation/security");

  const encryptionKey = process.env.ENCRYPTION_KEY;
  if (!encryptionKey) throw new Error("ENCRYPTION_KEY not configured");

  const mailbox = await prisma.mailbox.findUnique({
    where: { id: mailboxId },
  });

  if (!mailbox?.smtpHost || !mailbox.smtpPasswordEnc) {
    throw new Error("Mailbox SMTP not configured");
  }

  const smtpPassword = decrypt(mailbox.smtpPasswordEnc, encryptionKey);

  const smtp = new SmtpClient({
    host: mailbox.smtpHost,
    port: mailbox.smtpPort || 587,
    secure: mailbox.smtpPort === 465,
    auth: {
      user: mailbox.smtpUser || mailbox.emailAddress,
      pass: smtpPassword,
    },
  });

  const bodyWithFooter = `${draftBody}\n\n---\nThis reply was automatically generated by Emaily AI`;

  const replySubject = email.subject.startsWith("Re:")
    ? email.subject
    : `Re: ${email.subject}`;

  try {
    const sent = await smtp.sendReply(
      email.messageId,
      email.references,
      {
        from: mailbox.emailAddress,
        to: email.fromAddress,
        subject: replySubject,
        text: bodyWithFooter,
      }
    );

    // Save sent email to DB
    await prisma.email.create({
      data: {
        threadId: email.threadId,
        messageId: sent.messageId,
        inReplyTo: email.messageId,
        references: [...email.references, email.messageId],
        subject: replySubject,
        bodyText: bodyWithFooter,
        fromAddress: mailbox.emailAddress,
        toAddresses: [email.fromAddress],
        date: new Date(),
        folder: "Sent",
        isSent: true,
      },
    });

    await prisma.thread.update({
      where: { id: email.threadId },
      data: { hasSentReply: true, lastActivityAt: new Date() },
    });

    // Elevate sender trust when we reply
    const thread = await prisma.thread.findUnique({
      where: { id: email.threadId },
      select: { teamId: true },
    });
    if (thread) {
      await elevateTrustOnReply(thread.teamId, email.fromAddress);
    }

    return sent;
  } finally {
    smtp.close();
  }
}

// --- Main thread-based processing (single LLM call) ---

export async function processThreadWithAI(
  threadId: string,
  teamId: string,
  options?: { agentId?: string }
): Promise<AIProcessingResult> {
  const provider = getProvider();
  const autoTagger = new AutoTagger(provider);
  const unifiedProcessor = new UnifiedThreadProcessor(provider);

  const result: AIProcessingResult = {
    threadId,
    tagsApplied: [],
    intentsExtracted: [],
    draftGenerated: false,
    actionsExecuted: [],
  };

  try {
    // 1. Fetch thread with all emails + existing tags
    const thread = await prisma.thread.findUnique({
      where: { id: threadId },
      include: {
        mailbox: {
          include: {
            access: {
              where: { permission: { in: ["write", "admin"] } },
              take: 1,
            },
          },
        },
        emails: {
          orderBy: { date: "asc" },
          select: {
            id: true,
            messageId: true,
            subject: true,
            fromAddress: true,
            toAddresses: true,
            bodyText: true,
            date: true,
            references: true,
            isSent: true,
          },
        },
        tags: {
          include: { tag: true },
        },
      },
    });

    if (!thread || thread.emails.length === 0) {
      result.error = "Thread not found or has no emails";
      return result;
    }

    // Quarantine gate — don't process quarantined threads
    if (thread.status === "quarantined") {
      result.error = "Thread is quarantined (spam)";
      return result;
    }

    // 2. Fetch team tags + run deterministic rules
    const tags = await prisma.tag.findMany({
      where: { teamId, active: true },
    });

    const latestReceivedEmail = [...thread.emails].reverse().find((e) => !e.isSent);
    if (!latestReceivedEmail) {
      result.error = "No incoming emails in thread";
      return result;
    }

    // Resolve sender trust level
    const senderTrustLevel = await getSenderTrustLevel(teamId, latestReceivedEmail.fromAddress);

    const emailData = {
      subject: latestReceivedEmail.subject,
      from: latestReceivedEmail.fromAddress,
      to: latestReceivedEmail.toAddresses,
      body: latestReceivedEmail.bodyText,
    };

    const tagData = tags.map((t) => ({
      id: t.id,
      name: t.name,
      color: t.color,
      autoRules: t.autoRules as TagAutoRules | null,
    }));

    // Deterministic rule matching (0 LLM calls)
    const ruleMatches = autoTagger.evaluateRules(emailData, tagData);
    const ruleMatchedTagIds = new Set(ruleMatches.map((m) => m.tagId));

    // 3. Resolve agent
    let agent: { id: string; name: string; systemPrompt: string; temperature: number } | null = null;
    if (options?.agentId) {
      agent = await prisma.agent.findUnique({
        where: { id: options.agentId },
        select: { id: true, name: true, systemPrompt: true, temperature: true },
      });
    }
    if (!agent) {
      agent = await prisma.agent.findFirst({
        where: { teamId, isDefault: true, active: true },
        select: { id: true, name: true, systemPrompt: true, temperature: true },
      });
    }

    if (agent) {
      result.agentId = agent.id;
      result.agentName = agent.name;
    }

    // 4. Fetch approved Q&A pairs + existing context for the LLM
    const [qaPairs, existingActivity, teamComments, existingDraft] =
      await Promise.all([
        prisma.qAPair.findMany({
          where: { teamId, approved: true },
        }),
        prisma.activityLog.findMany({
          where: { targetType: "thread", targetId: threadId, userId: null },
          orderBy: { createdAt: "desc" },
          take: 20,
        }),
        prisma.comment.findMany({
          where: { threadId },
          include: { user: { select: { name: true } } },
          orderBy: { createdAt: "asc" },
          take: 20,
        }),
        prisma.sharedDraft.findFirst({
          where: { threadId, status: { not: "sent" } },
          select: { body: true },
        }),
      ]);

    // Build thread context so the AI knows what's already been done
    const threadContext = {
      existingTags: thread.tags.map((tt) => tt.tag.name),
      teamComments: teamComments.map((c) => ({
        author: c.user.name,
        text: c.content,
        date: c.createdAt.toISOString(),
      })),
      previousDraft: existingDraft?.body || null,
      senderTrust: senderTrustLevel === "vip"
        ? "Sender trust: vip — verified important contact"
        : senderTrustLevel === "trusted"
          ? "Sender trust: trusted — team has replied to this sender before"
          : senderTrustLevel === "known"
            ? "Sender trust: known — seen before but not yet replied to"
            : "Sender trust: stranger — unknown sender, be cautious with classifications",
      previousActivity: existingActivity.map((a) => {
        const meta = a.metadata as Record<string, unknown> | null;
        switch (a.action) {
          case "ai_tagged":
            return `Tagged: ${(meta?.tags as { name: string }[])?.map((t) => t.name).join(", ") || "unknown"}`;
          case "ai_draft_generated":
            return `Draft generated${meta?.agentName ? ` by ${meta.agentName}` : ""}`;
          case "ai_notified":
            return `Team notified (tag: ${meta?.tagName || "unknown"})`;
          case "ai_archived":
            return `Auto-archived (tag: ${meta?.tagName || "unknown"})`;
          case "ai_auto_replied":
            return `Auto-replied to ${meta?.sentTo || "sender"}`;
          default:
            return `${a.action}`;
        }
      }),
    };

    // 5. Single LLM call via UnifiedThreadProcessor
    // Filter tags by sender trust — only offer tags the sender qualifies for
    const senderTrustOrder = TRUST_LEVEL_ORDER[senderTrustLevel];
    const unmatchedTags = tags.filter(
      (t) =>
        !ruleMatchedTagIds.has(t.id) &&
        senderTrustOrder >= TRUST_LEVEL_ORDER[(t.minTrustLevel || "stranger") as TrustLevel]
    );
    const shouldDraft = tags.some(
      (t) =>
        (t.aiAction === "draft" || t.aiAction === "research_draft" || t.aiAction === "auto_reply") &&
        (ruleMatchedTagIds.has(t.id) || thread.tags.some((tt) => tt.tagId === t.id))
    ) || !!options?.agentId; // Always draft if agent explicitly requested

    const unifiedResult = await unifiedProcessor.processThread({
      subject: thread.emails[0].subject,
      emails: thread.emails.map((e) => ({
        from: e.fromAddress,
        body: e.bodyText,
        date: e.date,
        isSent: e.isSent,
      })),
      availableTags: unmatchedTags.map((t) => ({ name: t.name })),
      qaPairs: qaPairs.map((qa) => ({
        triggerPatterns: qa.triggerPatterns,
        idealResponse: qa.idealResponse,
      })),
      agentPersonality: agent?.systemPrompt || undefined,
      generateDraft: shouldDraft,
      replyTo: latestReceivedEmail.fromAddress,
      temperature: agent?.temperature,
      threadContext,
    });

    // 6. Resolve LLM tag matches to IDs
    const tagByNameLower = new Map(tags.map((t) => [t.name.toLowerCase(), t]));
    const llmTagMatches = unifiedResult.tags
      .map((t) => {
        const tag = tagByNameLower.get(t.name.toLowerCase());
        if (!tag) return null;
        return {
          tagId: tag.id,
          name: tag.name,
          confidence: t.confidence,
          appliedBy: "ai" as const,
        };
      })
      .filter((m): m is NonNullable<typeof m> => m !== null);

    const allTagMatches = [...ruleMatches, ...llmTagMatches];
    const newTagMatchIds = new Set(allTagMatches.map((m) => m.tagId));

    // Remove old AI-applied tags that are no longer matched, then upsert new ones
    const existingAITagIds = thread.tags
      .filter((tt) => tt.appliedBy === "ai")
      .map((tt) => tt.tagId);
    const tagsToRemove = existingAITagIds.filter((id) => !newTagMatchIds.has(id));

    await prisma.$transaction([
      // Remove stale AI tags
      ...(tagsToRemove.length > 0
        ? [
            prisma.threadTag.deleteMany({
              where: {
                threadId,
                tagId: { in: tagsToRemove },
                appliedBy: "ai",
              },
            }),
          ]
        : []),
      // Upsert current matches
      ...allTagMatches.map((match) =>
        prisma.threadTag.upsert({
          where: {
            threadId_tagId: {
              threadId,
              tagId: match.tagId,
            },
          },
          update: { appliedBy: match.appliedBy },
          create: {
            threadId,
            tagId: match.tagId,
            appliedBy: match.appliedBy,
          },
        })
      ),
    ]);

    // Determine which tags are genuinely new (not already on thread)
    const existingTagIds = new Set(thread.tags.map((tt) => tt.tagId));
    const genuinelyNewMatches = allTagMatches.filter(
      (m) => !existingTagIds.has(m.tagId)
    );

    if (allTagMatches.length > 0) {
      for (const match of allTagMatches) {
        result.tagsApplied.push({
          tagId: match.tagId,
          name: match.name,
          appliedBy: match.appliedBy,
          confidence: match.confidence,
        });
      }

      // Only log tag activity if there are actually new tags
      if (genuinelyNewMatches.length > 0 || tagsToRemove.length > 0) {
        await logAIActivity(teamId, threadId, "ai_tagged", {
          tags: result.tagsApplied.map((t) => ({
            name: t.name,
            confidence: t.confidence,
            appliedBy: t.appliedBy,
          })),
        });
      }
    }

    // 7. Save intents on latest received email
    result.intentsExtracted = unifiedResult.intents;

    if (unifiedResult.intents.length > 0) {
      await prisma.emailIntent.upsert({
        where: { emailId: latestReceivedEmail.id },
        update: {
          intents: JSON.parse(JSON.stringify(unifiedResult.intents)) as Prisma.InputJsonValue,
          modelVersion: provider.name,
        },
        create: {
          emailId: latestReceivedEmail.id,
          intents: JSON.parse(JSON.stringify(unifiedResult.intents)) as Prisma.InputJsonValue,
          modelVersion: provider.name,
        },
      });
    }

    // 8. Create or update SharedDraft with agentId if draft is not null
    if (unifiedResult.draft && thread.mailbox.access[0]) {
      const existingDraft = await prisma.sharedDraft.findFirst({
        where: {
          threadId,
          status: { not: "sent" },
        },
      });

      const draftData = {
        agentId: agent?.id ?? null,
        subject: unifiedResult.draft.subject,
        body: unifiedResult.draft.body,
        toAddresses: [latestReceivedEmail.fromAddress],
        status: "drafting",
        lockType: "generating",
        lockedById: null,
        lockExpiresAt: null,
        confidence: JSON.parse(
          JSON.stringify(unifiedResult.draft.confidence)
        ) as Prisma.InputJsonValue,
      };

      let draftId: string;
      if (existingDraft) {
        // Replace existing draft content with new agent's output
        await prisma.sharedDraft.update({
          where: { id: existingDraft.id },
          data: draftData,
        });
        draftId = existingDraft.id;
      } else {
        const created = await prisma.sharedDraft.create({
          data: {
            threadId,
            mailboxId: thread.mailbox.id,
            createdById: thread.mailbox.access[0].userId,
            ...draftData,
          },
        });
        draftId = created.id;
      }

      result.draftGenerated = true;
      result.draftId = draftId;

      await logAIActivity(teamId, threadId, "ai_draft_generated", {
        draftId,
        agentName: agent?.name,
      });
    }

    // 9. Execute tag actions — skip actions already performed (check activity log)
    const executedActionKeys = new Set(
      existingActivity.map((a) => {
        const meta = a.metadata as Record<string, unknown> | null;
        return `${a.action}:${meta?.tagName || ""}`;
      })
    );

    const activeTags = tags.filter((t) => newTagMatchIds.has(t.id));

    for (const tag of activeTags) {
      const match = allTagMatches.find((m) => m.tagId === tag.id);

      switch (tag.aiAction) {
        case "archive": {
          // Spam tag → quarantine instead of archive
          const isSpamTag = tag.name.toLowerCase() === "spam";
          const targetStatus = isSpamTag ? "quarantined" : "archived";
          const actionKey = isSpamTag ? "ai_quarantined" : "ai_archived";

          if (executedActionKeys.has(`${actionKey}:${tag.name}`)) break;
          await prisma.thread.update({
            where: { id: threadId },
            data: { status: targetStatus },
          });
          result.actionsExecuted.push({
            action: isSpamTag ? "quarantine" : "archive",
            tagId: tag.id,
            tagName: tag.name,
          });
          await logAIActivity(teamId, threadId, actionKey, {
            tagName: tag.name,
          });
          break;
        }

        case "auto_reply": {
          if (executedActionKeys.has(`ai_auto_replied:${tag.name}`)) break;
          // Safety: only auto-reply for rule-matched tags
          const isRuleMatched = match?.appliedBy === "auto" && match?.confidence === 1.0;
          if (!isRuleMatched) break;
          // Trust gate: never auto-reply to untrusted senders
          if (senderTrustOrder < TRUST_LEVEL_ORDER["trusted"]) break;

          if (unifiedResult.draft) {
            try {
              await sendAutoReply(
                {
                  threadId,
                  fromAddress: latestReceivedEmail.fromAddress,
                  messageId: latestReceivedEmail.messageId,
                  references: latestReceivedEmail.references,
                  subject: latestReceivedEmail.subject,
                },
                unifiedResult.draft.body,
                thread.mailbox.id
              );

              if (result.draftId) {
                await prisma.sharedDraft.update({
                  where: { id: result.draftId },
                  data: { status: "sent" },
                });
              }

              result.actionsExecuted.push({
                action: "auto_reply",
                tagId: tag.id,
                tagName: tag.name,
                detail: latestReceivedEmail.fromAddress,
              });
              await logAIActivity(teamId, threadId, "ai_auto_replied", {
                tagName: tag.name,
                sentTo: latestReceivedEmail.fromAddress,
              });
            } catch (err) {
              console.error(`[AI] Auto-reply failed for thread ${threadId}:`, err);
            }
          }
          break;
        }

        case "notify": {
          if (executedActionKeys.has(`ai_notified:${tag.name}`)) break;
          result.actionsExecuted.push({
            action: "notify",
            tagId: tag.id,
            tagName: tag.name,
          });
          await logAIActivity(teamId, threadId, "ai_notified", {
            tagName: tag.name,
          });
          break;
        }

        case "draft":
        case "research_draft": {
          // Draft already created above if applicable
          if (result.draftGenerated) {
            result.actionsExecuted.push({
              action: tag.aiAction,
              tagId: tag.id,
              tagName: tag.name,
            });
          }
          break;
        }

        default:
          break;
      }
    }
  } catch (error) {
    result.error = error instanceof Error ? error.message : "Unknown error";
    console.error(`[AI] Error processing thread ${threadId}:`, error);
  }

  return result;
}

// --- Legacy wrapper (resolves email → thread) ---

export async function processEmailWithAI(
  emailId: string,
  teamId: string
): Promise<AIProcessingResult> {
  const email = await prisma.email.findUnique({
    where: { id: emailId },
    select: { threadId: true },
  });

  if (!email) {
    return {
      threadId: emailId,
      tagsApplied: [],
      intentsExtracted: [],
      draftGenerated: false,
      actionsExecuted: [],
      error: "Email not found",
    };
  }

  return processThreadWithAI(email.threadId, teamId);
}

// --- Bulk thread-based processing ---

export async function processAllThreadsWithAI(
  teamId: string
): Promise<AIBulkProcessingResult> {
  // Find threads with unprocessed incoming emails (skip quarantined)
  const threadsWithUnprocessed = await prisma.thread.findMany({
    where: {
      mailbox: { teamId },
      status: { not: "quarantined" },
      emails: {
        some: {
          isSent: false,
          intents: { none: {} },
        },
      },
    },
    select: { id: true },
    orderBy: { lastActivityAt: "asc" },
  });

  const bulkResult: AIBulkProcessingResult = {
    total: threadsWithUnprocessed.length,
    processed: 0,
    errors: 0,
    results: [],
  };

  // Process in parallel batches of 5
  const CONCURRENCY = 5;
  for (let i = 0; i < threadsWithUnprocessed.length; i += CONCURRENCY) {
    const batch = threadsWithUnprocessed.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.allSettled(
      batch.map((thread) => processThreadWithAI(thread.id, teamId))
    );

    for (const r of batchResults) {
      if (r.status === "fulfilled") {
        bulkResult.results.push(r.value);
        if (r.value.error) bulkResult.errors++;
        else bulkResult.processed++;
      } else {
        bulkResult.errors++;
      }
    }
  }

  return bulkResult;
}

// Keep old name as alias for backward compatibility
export const processAllEmailsWithAI = processAllThreadsWithAI;

// --- Provider status ---

export async function getAIProviderStatus() {
  try {
    const provider = getProvider();
    const available = await provider.isAvailable();
    return {
      provider: provider.name,
      status: available ? "available" : "unavailable",
      model: provider.name === "gemini"
        ? process.env.GEMINI_MODEL || "gemini-2.5-flash"
        : process.env.OLLAMA_MODEL || "llama3.2",
    };
  } catch (error) {
    return {
      provider: "none",
      status: "error",
      model: null,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
