import { prisma } from "@/lib/prisma";
import type { Prisma } from "@emailautomation/database";
import {
  createProviderFromEnv,
  AutoTagger,
  UnifiedThreadProcessor,
  AgentLoop,
} from "@emailautomation/ai-engine";
import type { AIProvider } from "@emailautomation/ai-engine";
import type {
  TagAutoRules,
  AIProcessingResult,
  AIBulkProcessingResult,
  ActivityAction,
  TrustLevel,
} from "@emailautomation/shared";
import { TRUST_LEVEL_ORDER } from "@emailautomation/shared";
import { getSenderTrustLevel } from "@/lib/contacts";
import { elevateTrustOnReply } from "@/lib/contacts";
import { executeAgentTool } from "@/lib/agent-tools";

let providerInstance: AIProvider | null = null;

function getProvider(): AIProvider {
  if (!providerInstance) {
    providerInstance = createProviderFromEnv();
  }
  return providerInstance;
}

// --- Activity logging ---

async function logAIActivity(
  teamId: string,
  threadId: string,
  action: ActivityAction,
  metadata: Record<string, unknown> = {}
) {
  await prisma.activityLog.create({
    data: {
      teamId,
      userId: null,
      action,
      targetType: "thread",
      targetId: threadId,
      metadata: metadata as Prisma.InputJsonValue,
    },
  });
}

// --- Auto-reply ---

async function sendAutoReply(
  email: {
    threadId: string;
    fromAddress: string;
    messageId: string;
    references: string[];
    subject: string;
  },
  draftBody: string,
  mailboxId: string
) {
  const { SmtpClient } = await import("@emailautomation/mail-engine");
  const { decrypt } = await import("@emailautomation/security");

  const encryptionKey = process.env.ENCRYPTION_KEY;
  if (!encryptionKey) throw new Error("ENCRYPTION_KEY not configured");

  const mailbox = await prisma.mailbox.findUnique({
    where: { id: mailboxId },
  });

  if (!mailbox?.smtpHost || !mailbox.smtpPasswordEnc) {
    throw new Error("Mailbox SMTP not configured");
  }

  const smtpPassword = decrypt(mailbox.smtpPasswordEnc, encryptionKey);

  const smtp = new SmtpClient({
    host: mailbox.smtpHost,
    port: mailbox.smtpPort || 587,
    secure: mailbox.smtpPort === 465,
    auth: {
      user: mailbox.smtpUser || mailbox.emailAddress,
      pass: smtpPassword,
    },
  });

  const bodyWithFooter = `${draftBody}\n\n---\nThis reply was automatically generated by Emaily AI`;

  const replySubject = email.subject.startsWith("Re:")
    ? email.subject
    : `Re: ${email.subject}`;

  try {
    const sent = await smtp.sendReply(
      email.messageId,
      email.references,
      {
        from: mailbox.emailAddress,
        to: email.fromAddress,
        subject: replySubject,
        text: bodyWithFooter,
      }
    );

    // Save sent email to DB
    await prisma.email.create({
      data: {
        threadId: email.threadId,
        messageId: sent.messageId,
        inReplyTo: email.messageId,
        references: [...email.references, email.messageId],
        subject: replySubject,
        bodyText: bodyWithFooter,
        fromAddress: mailbox.emailAddress,
        toAddresses: [email.fromAddress],
        date: new Date(),
        folder: "Sent",
        isSent: true,
      },
    });

    await prisma.thread.update({
      where: { id: email.threadId },
      data: { hasSentReply: true, lastActivityAt: new Date() },
    });

    // Elevate sender trust when we reply
    const thread = await prisma.thread.findUnique({
      where: { id: email.threadId },
      select: { teamId: true },
    });
    if (thread) {
      await elevateTrustOnReply(thread.teamId, email.fromAddress);
    }

    return sent;
  } finally {
    smtp.close();
  }
}

// --- Main thread-based processing (agentic loop) ---

export async function processThreadWithAI(
  threadId: string,
  teamId: string,
  options?: { agentId?: string }
): Promise<AIProcessingResult> {
  const provider = getProvider();
  const autoTagger = new AutoTagger(provider);

  const result: AIProcessingResult = {
    threadId,
    tagsApplied: [],
    intentsExtracted: [],
    draftGenerated: false,
    actionsExecuted: [],
  };

  try {
    // 1. Fetch thread with all emails + existing tags + attachments + assignments
    const thread = await prisma.thread.findUnique({
      where: { id: threadId },
      include: {
        mailbox: {
          include: {
            access: {
              where: { permission: { in: ["write", "admin"] } },
              include: { user: { select: { name: true, email: true } } },
              take: 1,
            },
          },
        },
        emails: {
          orderBy: { date: "asc" },
          select: {
            id: true,
            messageId: true,
            subject: true,
            fromAddress: true,
            toAddresses: true,
            bodyText: true,
            date: true,
            references: true,
            isSent: true,
            attachments: {
              select: { filename: true, size: true, contentType: true },
            },
          },
        },
        tags: {
          include: { tag: true },
        },
        assignments: {
          include: {
            assignedTo: { select: { name: true } },
          },
        },
      },
    });

    if (!thread || thread.emails.length === 0) {
      result.error = "Thread not found or has no emails";
      return result;
    }

    // Quarantine gate — don't process quarantined threads
    if (thread.status === "quarantined") {
      result.error = "Thread is quarantined (spam)";
      return result;
    }

    // 2. Fetch team tags (with descriptions) + run deterministic rules
    const tags = await prisma.tag.findMany({
      where: { teamId, active: true },
    });

    const latestReceivedEmail = [...thread.emails].reverse().find((e) => !e.isSent);
    if (!latestReceivedEmail) {
      result.error = "No incoming emails in thread";
      return result;
    }

    // Resolve sender trust level
    const senderTrustLevel = await getSenderTrustLevel(teamId, latestReceivedEmail.fromAddress);

    const emailData = {
      subject: latestReceivedEmail.subject,
      from: latestReceivedEmail.fromAddress,
      to: latestReceivedEmail.toAddresses,
      body: latestReceivedEmail.bodyText,
    };

    const tagData = tags.map((tag) => ({
      id: tag.id,
      name: tag.name,
      color: tag.color,
      autoRules: tag.autoRules as TagAutoRules | null,
    }));

    // Deterministic rule matching (0 LLM calls)
    const ruleMatches = autoTagger.evaluateRules(emailData, tagData);
    const ruleMatchedTagIds = new Set(ruleMatches.map((m) => m.tagId));

    // 3. Resolve agent
    let agent: { id: string; name: string; systemPrompt: string; temperature: number } | null = null;
    if (options?.agentId) {
      agent = await prisma.agent.findUnique({
        where: { id: options.agentId },
        select: { id: true, name: true, systemPrompt: true, temperature: true },
      });
    }
    if (!agent) {
      agent = await prisma.agent.findFirst({
        where: { teamId, isDefault: true, active: true },
        select: { id: true, name: true, systemPrompt: true, temperature: true },
      });
    }

    if (agent) {
      result.agentId = agent.id;
      result.agentName = agent.name;
    }

    // 4. Fetch context: Q&A pairs, existing activity, team comments, existing draft, sender profile
    const [qaPairs, existingActivity, teamComments, existingDraft, senderContact] =
      await Promise.all([
        prisma.qAPair.findMany({
          where: { teamId, approved: true },
        }),
        prisma.activityLog.findMany({
          where: { targetType: "thread", targetId: threadId, userId: null },
          orderBy: { createdAt: "desc" },
          take: 20,
        }),
        prisma.comment.findMany({
          where: { threadId },
          include: { user: { select: { name: true } } },
          orderBy: { createdAt: "asc" },
          take: 20,
        }),
        prisma.sharedDraft.findFirst({
          where: { threadId, status: { not: "sent" } },
          select: { body: true },
        }),
        prisma.contact.findUnique({
          where: {
            teamId_email: {
              teamId,
              email: latestReceivedEmail.fromAddress.toLowerCase(),
            },
          },
        }),
      ]);

    // Compute thread age
    const now = new Date();
    const threadCreated = thread.createdAt;
    const ageDays = Math.round((now.getTime() - threadCreated.getTime()) / (1000 * 60 * 60 * 24));
    const lastActivityMs = now.getTime() - thread.lastActivityAt.getTime();
    const lastActivityHours = Math.round(lastActivityMs / (1000 * 60 * 60));
    const threadAge = `${ageDays} day(s) old, last activity ${lastActivityHours < 24 ? `${lastActivityHours} hour(s) ago` : `${Math.round(lastActivityHours / 24)} day(s) ago`}`;

    // Collect all attachments across emails
    const allAttachments = thread.emails.flatMap((e) =>
      e.attachments.map((attachment) => ({ filename: attachment.filename, size: attachment.size, contentType: attachment.contentType }))
    );

    // Build thread context
    const threadContext = {
      existingTags: thread.tags.map((tt) => tt.tag.name),
      teamComments: teamComments.map((comment) => ({
        author: comment.user.name,
        text: comment.content,
        date: comment.createdAt.toISOString(),
      })),
      previousDraft: existingDraft?.body || null,
      senderTrust: senderTrustLevel === "vip"
        ? "Sender trust: vip — verified important contact"
        : senderTrustLevel === "trusted"
          ? "Sender trust: trusted — team has replied to this sender before"
          : senderTrustLevel === "known"
            ? "Sender trust: known — seen before but not yet replied to"
            : "Sender trust: stranger — unknown sender, be cautious with classifications",
      previousActivity: existingActivity.map((activity) => {
        const meta = activity.metadata as Record<string, unknown> | null;
        switch (activity.action) {
          case "ai_tagged":
            return `Tagged: ${(meta?.tags as { name: string }[])?.map((tag) => tag.name).join(", ") || "unknown"}`;
          case "ai_draft_generated":
            return `Draft generated${meta?.agentName ? ` by ${meta.agentName}` : ""}`;
          case "ai_notified":
            return `Team notified (tag: ${meta?.tagName || "unknown"})`;
          case "ai_archived":
            return `Auto-archived (tag: ${meta?.tagName || "unknown"})`;
          case "ai_auto_replied":
            return `Auto-replied to ${meta?.sentTo || "sender"}`;
          default:
            return `${activity.action}`;
        }
      }),
      senderProfile: senderContact
        ? {
            name: senderContact.name,
            company: senderContact.company,
            domain: senderContact.domain,
            interactionCount: senderContact.interactionCount,
            repliedToCount: senderContact.repliedToCount,
            notes: senderContact.notes,
          }
        : undefined,
      assignments: thread.assignments.map((assignment) => ({
        assignedTo: assignment.assignedTo.name,
        status: assignment.status,
        note: assignment.note,
        dueDate: assignment.dueDate?.toISOString() || null,
      })),
      attachments: allAttachments.length > 0 ? allAttachments : undefined,
      threadAge,
    };

    // 5. Run AgentLoop instead of single UnifiedThreadProcessor call
    // Filter tags by sender trust
    const senderTrustOrder = TRUST_LEVEL_ORDER[senderTrustLevel];
    const unmatchedTags = tags.filter(
      (tag) =>
        !ruleMatchedTagIds.has(tag.id) &&
        senderTrustOrder >= TRUST_LEVEL_ORDER[(tag.minTrustLevel || "stranger") as TrustLevel]
    );
    const shouldDraft = tags.some(
      (tag) =>
        (tag.aiAction === "draft" || tag.aiAction === "research_draft" || tag.aiAction === "auto_reply") &&
        (ruleMatchedTagIds.has(tag.id) || thread.tags.some((tt) => tt.tagId === tag.id))
    ) || !!options?.agentId;

    const agentLoop = new AgentLoop(provider);
    const loopResult = await agentLoop.run(
      {
        subject: thread.emails[0].subject,
        emails: thread.emails.map((e) => ({
          from: e.fromAddress,
          body: e.bodyText,
          date: e.date,
          isSent: e.isSent,
        })),
        availableTags: unmatchedTags.map((tag) => ({
          name: tag.name,
          description: (tag as Record<string, unknown>).description as string | undefined,
          aiAction: tag.aiAction,
        })),
        qaPairs: qaPairs.map((qa) => ({
          triggerPatterns: qa.triggerPatterns,
          idealResponse: qa.idealResponse,
        })),
        agentPersonality: agent?.systemPrompt || undefined,
        generateDraft: shouldDraft,
        replyTo: latestReceivedEmail.fromAddress,
        temperature: agent?.temperature,
        threadContext,
        agentName: agent?.name,
        userName: thread.mailbox.access[0]?.user?.name,
        userEmail: thread.mailbox.access[0]?.user?.email,
      },
      teamId,
      executeAgentTool
    );

    const decision = loopResult.decision;

    // Log agent reasoning trail
    await logAIActivity(teamId, threadId, "ai_tagged", {
      agentLoop: true,
      totalIterations: loopResult.totalIterations,
      tags: decision.tags.map((tag) => ({ name: tag.name, confidence: tag.confidence })),
      agentName: agent?.name,
      triage: decision.triage,
    });

    // 6. Resolve LLM tag matches to IDs
    const tagByNameLower = new Map(tags.map((tag) => [tag.name.toLowerCase(), tag]));
    const llmTagMatches = decision.tags
      .map((decisionTag) => {
        const matchedTag = tagByNameLower.get(decisionTag.name.toLowerCase());
        if (!matchedTag) return null;
        return {
          tagId: matchedTag.id,
          name: matchedTag.name,
          confidence: decisionTag.confidence,
          appliedBy: "ai" as const,
        };
      })
      .filter((match): match is NonNullable<typeof match> => match !== null);

    const allTagMatches = [...ruleMatches, ...llmTagMatches];
    const newTagMatchIds = new Set(allTagMatches.map((m) => m.tagId));

    // Remove old AI-applied tags that are no longer matched, then upsert new ones
    const existingAITagIds = thread.tags
      .filter((tt) => tt.appliedBy === "ai")
      .map((tt) => tt.tagId);
    const tagsToRemove = existingAITagIds.filter((id) => !newTagMatchIds.has(id));

    await prisma.$transaction([
      ...(tagsToRemove.length > 0
        ? [
            prisma.threadTag.deleteMany({
              where: {
                threadId,
                tagId: { in: tagsToRemove },
                appliedBy: "ai",
              },
            }),
          ]
        : []),
      ...allTagMatches.map((match) =>
        prisma.threadTag.upsert({
          where: {
            threadId_tagId: {
              threadId,
              tagId: match.tagId,
            },
          },
          update: { appliedBy: match.appliedBy },
          create: {
            threadId,
            tagId: match.tagId,
            appliedBy: match.appliedBy,
          },
        })
      ),
    ]);

    if (allTagMatches.length > 0) {
      for (const match of allTagMatches) {
        result.tagsApplied.push({
          tagId: match.tagId,
          name: match.name,
          appliedBy: match.appliedBy,
          confidence: match.confidence,
        });
      }
    }

    // 7. Save intents on latest received email
    result.intentsExtracted = decision.intents;

    if (decision.intents.length > 0) {
      await prisma.emailIntent.upsert({
        where: { emailId: latestReceivedEmail.id },
        update: {
          intents: JSON.parse(JSON.stringify(decision.intents)) as Prisma.InputJsonValue,
          modelVersion: provider.name,
        },
        create: {
          emailId: latestReceivedEmail.id,
          intents: JSON.parse(JSON.stringify(decision.intents)) as Prisma.InputJsonValue,
          modelVersion: provider.name,
        },
      });
    }

    // 8. AgentTagWatch routing — check if a specialist should re-draft
    let draftResult = decision.draft;
    let draftAgent = agent;

    if (allTagMatches.length > 0 && !options?.agentId) {
      const tagWatches = await prisma.agentTagWatch.findMany({
        where: {
          tagId: { in: allTagMatches.map((m) => m.tagId) },
          agent: { active: true },
        },
        include: {
          agent: { select: { id: true, name: true, systemPrompt: true, temperature: true } },
          tag: { select: { name: true } },
        },
      });

      if (tagWatches.length > 0) {
        // Pick specialist with highest-confidence tag match
        let bestWatch = tagWatches[0];
        let bestConfidence = 0;
        for (const watch of tagWatches) {
          const match = allTagMatches.find((m) => m.tagId === watch.tagId);
          if (match && match.confidence > bestConfidence) {
            bestConfidence = match.confidence;
            bestWatch = watch;
          }
        }

        const specialist = bestWatch.agent;

        // Only re-draft if specialist is different from current agent
        if (specialist.id !== agent?.id && shouldDraft) {
          // Re-run draft generation only with specialist's personality
          const specialistProcessor = new UnifiedThreadProcessor(provider);
          const specialistResult = await specialistProcessor.processThread({
            subject: thread.emails[0].subject,
            emails: thread.emails.map((e) => ({
              from: e.fromAddress,
              body: e.bodyText,
              date: e.date,
              isSent: e.isSent,
            })),
            availableTags: [],
            qaPairs: qaPairs.map((qa) => ({
              triggerPatterns: qa.triggerPatterns,
              idealResponse: qa.idealResponse,
            })),
            agentPersonality: specialist.systemPrompt,
            generateDraft: true,
            replyTo: latestReceivedEmail.fromAddress,
            temperature: specialist.temperature,
            threadContext,
          });

          if (specialistResult.draft) {
            draftResult = specialistResult.draft;
            draftAgent = specialist;
            result.agentId = specialist.id;
            result.agentName = specialist.name;

            await logAIActivity(teamId, threadId, "ai_agent_routed", {
              fromAgent: agent?.name || "default",
              toAgent: specialist.name,
              matchedTag: bestWatch.tag.name,
              reason: `Specialist routing via AgentTagWatch (confidence: ${bestConfidence})`,
            });
          }
        }
      }
    }

    // 9. Create or update SharedDraft
    if (draftResult && thread.mailbox.access[0]) {
      const existingDraftRecord = await prisma.sharedDraft.findFirst({
        where: {
          threadId,
          status: { not: "sent" },
        },
      });

      const draftData = {
        agentId: draftAgent?.id ?? null,
        subject: draftResult.subject,
        body: draftResult.body,
        toAddresses: [latestReceivedEmail.fromAddress],
        status: "drafting",
        lockType: "generating",
        lockedById: null,
        lockExpiresAt: null,
        confidence: JSON.parse(
          JSON.stringify(draftResult.confidence)
        ) as Prisma.InputJsonValue,
      };

      let draftId: string;
      if (existingDraftRecord) {
        await prisma.sharedDraft.update({
          where: { id: existingDraftRecord.id },
          data: draftData,
        });
        draftId = existingDraftRecord.id;
      } else {
        const created = await prisma.sharedDraft.create({
          data: {
            threadId,
            mailboxId: thread.mailbox.id,
            createdById: thread.mailbox.access[0].userId,
            ...draftData,
          },
        });
        draftId = created.id;
      }

      result.draftGenerated = true;
      result.draftId = draftId;

      await logAIActivity(teamId, threadId, "ai_draft_generated", {
        draftId,
        agentName: draftAgent?.name,
      });
    }

    // 10. Store triage on thread
    await prisma.thread.update({
      where: { id: threadId },
      data: {
        aiPriority: decision.triage.priority,
        aiNeedsReply: decision.triage.needsReply,
        aiStatus: decision.escalate ? "needs_attention" : "processed",
      },
    });

    // 11. Handle escalation
    if (decision.escalate) {
      await logAIActivity(teamId, threadId, "ai_needs_attention", {
        reason: decision.escalation?.reason || "Agent escalated",
        suggestedAction: decision.escalation?.suggestedAction || "Review manually",
        partialWork: decision.escalation?.partialWork
          ? { tags: decision.escalation.partialWork.tags?.length || 0 }
          : undefined,
      });
    }

    // 12. Execute tag actions with triage safety checks
    const executedActionKeys = new Set(
      existingActivity.map((activity) => {
        const meta = activity.metadata as Record<string, unknown> | null;
        return `${activity.action}:${meta?.tagName || ""}`;
      })
    );

    const activeTags = tags.filter((tag) => newTagMatchIds.has(tag.id));

    for (const tag of activeTags) {
      const match = allTagMatches.find((m) => m.tagId === tag.id);

      switch (tag.aiAction) {
        case "archive": {
          // Safety: block archive on high-priority threads
          if (decision.triage.priority === "high") {
            result.actionsExecuted.push({
              action: "archive",
              tagId: tag.id,
              tagName: tag.name,
              detail: "blocked by triage: high priority",
            });
            break;
          }

          // Safety: don't archive if a draft was generated — user should see it first
          if (result.draftGenerated) {
            result.actionsExecuted.push({
              action: "archive",
              tagId: tag.id,
              tagName: tag.name,
              detail: "blocked: draft generated, user should review first",
            });
            break;
          }

          // Safety: don't archive if triage says reply is needed
          if (decision.triage.needsReply) {
            result.actionsExecuted.push({
              action: "archive",
              tagId: tag.id,
              tagName: tag.name,
              detail: "blocked: triage says reply needed",
            });
            break;
          }

          const isSpamTag = tag.name.toLowerCase() === "spam";
          const targetStatus = isSpamTag ? "quarantined" : "archived";
          const actionKey = isSpamTag ? "ai_quarantined" : "ai_archived";

          if (executedActionKeys.has(`${actionKey}:${tag.name}`)) break;
          await prisma.thread.update({
            where: { id: threadId },
            data: { status: targetStatus },
          });
          result.actionsExecuted.push({
            action: isSpamTag ? "quarantine" : "archive",
            tagId: tag.id,
            tagName: tag.name,
          });
          await logAIActivity(teamId, threadId, actionKey, {
            tagName: tag.name,
          });
          break;
        }

        case "auto_reply": {
          if (executedActionKeys.has(`ai_auto_replied:${tag.name}`)) break;
          const isRuleMatched = match?.appliedBy === "auto" && match?.confidence === 1.0;
          if (!isRuleMatched) break;
          if (senderTrustOrder < TRUST_LEVEL_ORDER["trusted"]) break;

          if (draftResult) {
            try {
              await sendAutoReply(
                {
                  threadId,
                  fromAddress: latestReceivedEmail.fromAddress,
                  messageId: latestReceivedEmail.messageId,
                  references: latestReceivedEmail.references,
                  subject: latestReceivedEmail.subject,
                },
                draftResult.body,
                thread.mailbox.id
              );

              if (result.draftId) {
                await prisma.sharedDraft.update({
                  where: { id: result.draftId },
                  data: { status: "sent" },
                });
              }

              result.actionsExecuted.push({
                action: "auto_reply",
                tagId: tag.id,
                tagName: tag.name,
                detail: latestReceivedEmail.fromAddress,
              });
              await logAIActivity(teamId, threadId, "ai_auto_replied", {
                tagName: tag.name,
                sentTo: latestReceivedEmail.fromAddress,
              });
            } catch (err) {
              console.error(`[AI] Auto-reply failed for thread ${threadId}:`, err);
            }
          }
          break;
        }

        case "notify": {
          if (executedActionKeys.has(`ai_notified:${tag.name}`)) break;
          result.actionsExecuted.push({
            action: "notify",
            tagId: tag.id,
            tagName: tag.name,
          });
          await logAIActivity(teamId, threadId, "ai_notified", {
            tagName: tag.name,
          });
          break;
        }

        case "draft":
        case "research_draft": {
          // Triage safety: skip draft on needsReply=false threads
          if (!decision.triage.needsReply) {
            result.actionsExecuted.push({
              action: tag.aiAction,
              tagId: tag.id,
              tagName: tag.name,
              detail: "skipped: triage says no reply needed",
            });
            break;
          }

          if (result.draftGenerated) {
            result.actionsExecuted.push({
              action: tag.aiAction,
              tagId: tag.id,
              tagName: tag.name,
            });
          }
          break;
        }

        default:
          break;
      }
    }
  } catch (error) {
    result.error = error instanceof Error ? error.message : "Unknown error";
    console.error(`[AI] Error processing thread ${threadId}:`, error);
  }

  return result;
}

// --- Legacy wrapper (resolves email → thread) ---

export async function processEmailWithAI(
  emailId: string,
  teamId: string
): Promise<AIProcessingResult> {
  const email = await prisma.email.findUnique({
    where: { id: emailId },
    select: { threadId: true },
  });

  if (!email) {
    return {
      threadId: emailId,
      tagsApplied: [],
      intentsExtracted: [],
      draftGenerated: false,
      actionsExecuted: [],
      error: "Email not found",
    };
  }

  return processThreadWithAI(email.threadId, teamId);
}

// --- Bulk thread-based processing ---

export async function processAllThreadsWithAI(
  teamId: string
): Promise<AIBulkProcessingResult> {
  // Find threads with unprocessed incoming emails (skip quarantined)
  const threadsWithUnprocessed = await prisma.thread.findMany({
    where: {
      mailbox: { teamId },
      status: { not: "quarantined" },
      emails: {
        some: {
          isSent: false,
          intents: { none: {} },
        },
      },
    },
    select: { id: true },
    orderBy: { lastActivityAt: "asc" },
  });

  const bulkResult: AIBulkProcessingResult = {
    total: threadsWithUnprocessed.length,
    processed: 0,
    errors: 0,
    results: [],
  };

  // Process in parallel batches of 5
  const CONCURRENCY = 5;
  for (let i = 0; i < threadsWithUnprocessed.length; i += CONCURRENCY) {
    const batch = threadsWithUnprocessed.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.allSettled(
      batch.map((thread) => processThreadWithAI(thread.id, teamId))
    );

    for (const r of batchResults) {
      if (r.status === "fulfilled") {
        bulkResult.results.push(r.value);
        if (r.value.error) bulkResult.errors++;
        else bulkResult.processed++;
      } else {
        bulkResult.errors++;
      }
    }
  }

  return bulkResult;
}

// Keep old name as alias for backward compatibility
export const processAllEmailsWithAI = processAllThreadsWithAI;

// --- Provider status ---

export async function getAIProviderStatus() {
  try {
    const provider = getProvider();
    const available = await provider.isAvailable();
    return {
      provider: provider.name,
      status: available ? "available" : "unavailable",
      model: provider.name === "gemini"
        ? process.env.GEMINI_MODEL || "gemini-2.5-flash"
        : process.env.OLLAMA_MODEL || "llama3.2",
    };
  } catch (error) {
    return {
      provider: "none",
      status: "error",
      model: null,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}
