"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Loader2,
  Sparkles,
  Tag,
  FileEdit,
  Send,
  Archive,
  Bell,
  ChevronDown,
  Bot,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useAgents } from "@/hooks/use-agents";
import { revalidateAll } from "@/lib/revalidate";

interface AIActivity {
  id: string;
  action: string;
  metadata: Record<string, unknown>;
  createdAt: string;
}

interface AIActivityPanelProps {
  threadId: string;
}

const actionConfig: Record<
  string,
  {
    label: string;
    icon: React.ComponentType<{ className?: string }>;
    color: string;
    format: (meta: Record<string, unknown>) => string;
  }
> = {
  ai_tagged: {
    label: "Tagged",
    icon: Tag,
    color: "text-blue-600 bg-blue-50 border-blue-200",
    format: (meta) => {
      const tags = meta.tags as { name: string; confidence: number }[] | undefined;
      if (!tags?.length) return "Applied tags";
      return tags
        .map((t) => `${t.name} (${Math.round(t.confidence * 100)}%)`)
        .join(", ");
    },
  },
  ai_draft_generated: {
    label: "Draft Generated",
    icon: FileEdit,
    color: "text-green-600 bg-green-50 border-green-200",
    format: (meta) => {
      const agentName = meta.agentName as string | undefined;
      return agentName
        ? `Draft generated by ${agentName}`
        : "Generated draft reply";
    },
  },
  ai_auto_replied: {
    label: "Auto-replied",
    icon: Send,
    color: "text-amber-600 bg-amber-50 border-amber-200",
    format: (meta) => `Auto-replied to ${meta.sentTo || "sender"}`,
  },
  ai_archived: {
    label: "Archived",
    icon: Archive,
    color: "text-zinc-600 bg-zinc-50 border-zinc-200",
    format: (meta) => `Auto-archived (tag: ${meta.tagName || "unknown"})`,
  },
  ai_notified: {
    label: "Notified",
    icon: Bell,
    color: "text-purple-600 bg-purple-50 border-purple-200",
    format: (meta) => `Team notified (tag: ${meta.tagName || "unknown"})`,
  },
};

export function AIActivityPanel({ threadId }: AIActivityPanelProps) {
  const router = useRouter();
  const [activities, setActivities] = useState<AIActivity[]>([]);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [selectedAgentId, setSelectedAgentId] = useState<string | null>(null);
  const [result, setResult] = useState<{
    tags: number;
    intents: number;
    draft: boolean;
    actions: number;
    agentName?: string;
  } | null>(null);
  const { agents } = useAgents();

  const activeAgents = agents?.filter((a) => a.active) ?? [];
  const selectedAgent = selectedAgentId
    ? activeAgents.find((a) => a.id === selectedAgentId)
    : activeAgents.find((a) => a.isDefault);

  const activityCountRef = useRef(0);

  const fetchActivities = useCallback(async () => {
    try {
      const res = await fetch(`/api/threads/${threadId}/ai-activity`);
      if (res.ok) {
        const data = await res.json();
        setActivities(data);
        // If activity count changed, refresh the whole page to update tags/drafts/etc.
        if (data.length !== activityCountRef.current) {
          activityCountRef.current = data.length;
          revalidateAll();
          router.refresh();
        }
      }
    } catch {
      // Silently fail
    } finally {
      setLoading(false);
    }
  }, [threadId, router]);

  // Continuous polling: 2s while processing, 5s otherwise
  useEffect(() => {
    fetchActivities();
    const interval = setInterval(
      () => fetchActivities(),
      processing ? 2000 : 5000
    );
    return () => clearInterval(interval);
  }, [fetchActivities, processing]);

  async function handleProcess(agentId?: string) {
    setProcessing(true);
    setResult(null);

    try {
      const res = await fetch("/api/ai/process", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          threadId,
          agentId: agentId || selectedAgent?.id,
        }),
      });

      if (res.ok) {
        const data = await res.json();
        setResult(data.result ?? null);
      }
    } catch {
      // ignore
    } finally {
      setProcessing(false);
      await fetchActivities();
      revalidateAll();
      router.refresh();
    }
  }

  if (loading) {
    return (
      <div className="text-xs text-muted-foreground">Loading AI activity...</div>
    );
  }

  return (
    <div className="space-y-2">
      <div className="flex gap-1">
        <Button
          variant="outline"
          size="sm"
          className="flex-1 gap-2"
          onClick={() => handleProcess()}
          disabled={processing}
        >
          {processing ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Sparkles className="h-3.5 w-3.5" />
          )}
          {processing ? "Processing..." : "Analyze with AI"}
        </Button>

        {activeAgents.length > 0 && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="gap-1 px-2"
                disabled={processing}
              >
                <Bot className="h-3.5 w-3.5" />
                <ChevronDown className="h-3 w-3" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {activeAgents.map((agent) => (
                <DropdownMenuItem
                  key={agent.id}
                  onClick={() => {
                    setSelectedAgentId(agent.id);
                    handleProcess(agent.id);
                  }}
                >
                  <Bot className="mr-2 h-3.5 w-3.5" />
                  {agent.name}
                  {agent.isDefault && (
                    <Badge variant="secondary" className="ml-2 text-[10px] px-1 py-0">
                      default
                    </Badge>
                  )}
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        )}
      </div>

      {result && (
        <div className="rounded border bg-muted/50 px-2 py-1.5 text-xs text-muted-foreground">
          {result.agentName && (
            <span className="font-medium">{result.agentName}: </span>
          )}
          {result.tags > 0 && <span>{result.tags} tag(s) applied. </span>}
          {result.intents > 0 && <span>{result.intents} intent(s) found. </span>}
          {result.draft && <span>Draft generated. </span>}
          {result.actions > 0 && <span>{result.actions} action(s) executed. </span>}
          {result.tags === 0 && result.intents === 0 && !result.draft && (
            <span>No results.</span>
          )}
        </div>
      )}

      {activities.length === 0 ? (
        <div className="text-xs text-muted-foreground">No AI activity yet</div>
      ) : (
        activities.map((activity) => {
          const config = actionConfig[activity.action];
          if (!config) return null;

          const Icon = config.icon;
          const description = config.format(
            activity.metadata as Record<string, unknown>
          );
          const timeAgo = formatTimeAgo(activity.createdAt);

          return (
            <div
              key={activity.id}
              className="flex items-start gap-2 rounded border px-2 py-1.5 text-xs"
            >
              <div className={cn("mt-0.5 rounded p-0.5", config.color)}>
                <Icon className="h-3 w-3" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="leading-snug text-foreground">{description}</p>
                <p className="mt-0.5 text-muted-foreground">{timeAgo}</p>
              </div>
            </div>
          );
        })
      )}
    </div>
  );
}

function formatTimeAgo(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMin = Math.floor(diffMs / 60000);

  if (diffMin < 1) return "just now";
  if (diffMin < 60) return `${diffMin}m ago`;
  const diffHours = Math.floor(diffMin / 60);
  if (diffHours < 24) return `${diffHours}h ago`;
  const diffDays = Math.floor(diffHours / 24);
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString();
}
